name: simple-python-script
desc: Find integer array mean
cmd: python main.py --data ${DATA} --result ${OUTPUT}
env:
  python: auto
inputs:
  - numbers.txt: DATA
outputs:
  - result.txt: OUTPUT
  - metrics.txt
