name: nemo-docker-gpu
desc: Learn text classification model on GPU using NeMo docker image
cmd: >
  python /workspace/nemo/examples/nlp/text_classification/text_classification_with_bert.py
    model.dataset.num_classes=2
    model.train_ds.file_path=${TRAIN}
    model.validation_ds.file_path=${DEV}
    trainer.max_epochs=2
    trainer.devices=2
    trainer.accelerator='gpu'
env:
  docker:
    image: nvcr.io/nvidia/nemo:23.06
inputs:
  - train.tsv: TRAIN
  - dev.tsv: DEV
outputs:
  - text_classification_model.nemo:
cloud-instance-type: g1.2
